---
name: Build ruby-on-rails image

on:
  push:
    paths:
      - .github/workflows/ruby-on-rails.yml
      - images/ruby-on-rails/**
    branches:
      - main

jobs:
  build-main-image:
    uses: ./.github/workflows/build.yml
    with:
      image_path: ruby-on-rails
  #
  # build-dev-image:
  #   name: Build debug image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #
  #     - uses: ./.github/workflows/build.yml
  #       with:
  #         image_path: ruby-on-rails
  #         output_tag: debug
  #         build_args: |
  #           ADD_DEBUG_PKGS=yes
